### ISSUE TITLE
Choosing Expert Roles

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#1]
All developers are responsible for the whole project and will all co-work at all tasks. Nevertheless each developer has an expert role for one specific continuing task. We have the following expert roles. Everyone selects one role and posts here what role he or she has.

REQ-Expert (requirements)
main communication person for customer
requirements documentation and tracking
responsible for product backlog and sprint backlog

UI-Expert (user interface)
look and feel of application
usability
enduser documentation/tutorials

ARC-Expert (software architect)
documentation of architecture
documentation of data structure
continuous check of architecture

CM-Expert (configuration management)
structure of repository
branching/merging concept
tracking of branches
admin of GutHub project

TST-Expert (test expert)
responsible for test suites and test cases
regular manual run of tests
documenting lack of tests
code coverage (glass box tests)

QA-Expert (quality assurance)
organization and check of reviews
code-reviews and sprint-reviews
sprint retrospective

DOC-Expert (documentation)
technical documentation
license
code comments

RULE-Expert (rules of the game)
documentation of game story and game rules
in coordination with all other developers

ADV-Expert (advertising)
planning of advertising the project
website, demo-video, social network

SCA-Expert (static code analysis)
definition of static code analysis tool
regular check of findings
code conventions

**Comment by ibogicevic** [comment]
Estimated Efforts: 2h/0,5h

**Comment by M320Trololol** [comment]
Calling Dibs on RULE-Expert

**Comment by DorianCzichotzki** [comment]
ARC-Expert

**Comment by Xerf1** [comment]
UI-Expert

**Comment by smilingGirl** [comment]
Nooooo I want to be story person

**Comment by ThoreKr** [comment]
Wanna take care of the CM

**Comment by johannaSommer** [comment]
REQ i guess

**Comment by johannaSommer** [comment]
falls das jemand will mach ich aber auch ADV

**Comment by CathleenSch** [comment]
TST

**Comment by Oswaldbob** [comment]
SCA-Expert (static code analysis)

**Comment by smilingGirl** [comment]
ADV I guess?

**Comment by hemutsneck** [comment]
DOC-Expert

**Comment by danielrutz** [comment]
QA

**Comment by danielrutz** [comment]
Closed as all roles are assigned now.
