### ISSUE TITLE
Evaluation of Static Code Analysis tool

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#10]
Evaluate which static code analysis tool we want to use in the project and add this information to our file process.md.

**Comment by ibogicevic** [comment]
Estimated Efforts: 1h/2h

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #10: Evaluation of Static Code Analysis tool](https://trello.com/c/okS5cEdX/13-issue-10-evaluation-of-static-code-analysis-tool)

**Comment by Oswaldbob** [comment]
Evaluation result:
Sonarlint + Sonarcloud

Implementation next

**Comment by Oswaldbob** [comment]
Added Description of Setup and Usage here:
https://github.com/dhbw-stginf16a/Rebleyama/wiki/Project-Setup

Everything related to Static Code Analysis is done for now.
Potentially:  In the future Sonarcloud could be connected to SonarLint configs of project users. 

Close #10
