### ISSUE TITLE
Evaluation of hexagonal fields

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#11]
Evaluate effort difference between rectangular and hexagonal game fields and decide which type we want to take.

**Comment by ibogicevic** [comment]
Estimated Efforts: 1h/3h

**Comment by Xerf1** [comment]
![image](https://user-images.githubusercontent.com/5603062/37403668-e1ad200a-278f-11e8-9d47-dd2320c10677.png)

**For more infos visit** https://www.redblobgames.com/grids/hexagons/

**To _Vote_ on what were using visit** https://www.strawpoll.me/15268040

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #11: Evaluation of hexagonal fields](https://trello.com/c/pHfYm4QL/14-issue-11-evaluation-of-hexagonal-fields)

**Comment by Xerf1** [comment]
The team voted for **square fields**. Issue closed.
