### ISSUE TITLE
Game Field Definition

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#12]
Define what types the field in the game area can be. There should be about 5 types at the beginning.

**Comment by ibogicevic** [comment]
Estimated Efforts: 1h/0,5h
Subtask of #3

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #12: Game Field Definition](https://trello.com/c/GXTanYM5/15-issue-12-game-field-definition)

**Comment by M320Trololol** [comment]
Done via #39
