### ISSUE TITLE
Field Content Definition

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#13]
Define what items can be on a field.

**Comment by ibogicevic** [comment]
Estimated Efforts: 2h/2h

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #13: Field Content Definition](https://trello.com/c/wXEVhk0i/16-issue-13-field-content-definition)

**Comment by M320Trololol** [comment]
Done via https://github.com/dhbw-stginf16a/Rebleyama/wiki/Definition-of-Game
