### ISSUE TITLE
Game Field Textures

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#14]
Draw the textures for the different types of game field as LibreOffice-files (odg) and export them as 40x40 pixels png.

**Comment by ibogicevic** [comment]
Estimated Efforts: 5h/3h

**Comment by M320Trololol** [comment]
Dependent on #12

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #14: Game Field Textures](https://trello.com/c/VtciCq2e/17-issue-14-game-field-textures)

**Comment by M320Trololol** [comment]
Done via #27 #38 and #40
