### ISSUE TITLE
Field Content Drawings

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#15]
Draw the items that can be on a game field as LibreOffice-files (odg) and export them as 40x40 pixels png.

**Comment by ibogicevic** [comment]
Estimated Efforts: 13h/8h

**Comment by M320Trololol** [comment]
Dependent on #13

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #15: Field Content Drawings](https://trello.com/c/GOj1aQGN/18-issue-15-field-content-drawings)

**Comment by M320Trololol** [comment]
Advanced via #38

**Comment by ibogicevic** [comment]
Sufficient for the first gameplay. Nice drawings!
