### ISSUE TITLE
Game Logo

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#16]
Draw a game logo in LibreOffice-format (odg) and include it in the application and on the GitHub-Website.

**Comment by ibogicevic** [comment]
Estimated Efforts: 2h/3h

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #16: Game Logo](https://trello.com/c/3PjKfQR1/19-issue-16-game-logo)

**Comment by ibogicevic** [comment]
Finished. Nice Logo!
