### ISSUE TITLE
Evaluation of UI library

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#17]
Evaluate and decide which UI library/technique we want to use in our main JavaFX-frame. Be ware that we only have 2D objects and that gameplay framerate needn't be high.

**Comment by ibogicevic** [comment]
Estimated Efforts: 1h(see #5)/3h

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #17: Evaluation of UI library](https://trello.com/c/SIe9gzAN/20-issue-17-evaluation-of-ui-library)

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #17: Evaluation of UI library](https://trello.com/c/SIe9gzAN/20-issue-17-evaluation-of-ui-library)

**Comment by danielrutz** [comment]
I would recommend to use libgdx (https://libgdx.badlogicgames.com/) as a framework.
LWJGL looks too low-level for our purposes; it would require too much boilerplate code.
jMonkeyEngine looks like it is focused too much on 3D; it could be hard to adopt it for 2D graphics.
