### ISSUE TITLE
Implementation of Game Area

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#18]
Implement a simple rectangular game field with 512x512 fields with 40x40 pixels each. The fields can be of several types. Each type is associated a specific texture.

**Comment by ibogicevic** [comment]
Estimated Efforts: 5h/5h

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #18: Implementation of Game Area](https://trello.com/c/24S0BLzq/21-issue-18-implementation-of-game-area)

**Comment by M320Trololol** [comment]
Closed via #39 and #41
