### ISSUE TITLE
Documentation Format Evaluation

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#2]
Evaluate different documentation formats (e.g. markdown, wiki) which would be appropriate for our project (both for technical and non-technical documentation) and decide for one.

**Comment by ibogicevic** [comment]
Estimated Efforts: 1h/0,5h

**Comment by ibogicevic** [comment]
In case we use markdown, we should consider using the following template for all architectural/tool/library decisions: https://adr.github.io/madr/

**Comment by M320Trololol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation Format Evaluation](https://trello.com/c/rXMYBkRh/4-documentation-format-evaluation)

**Comment by M320Trololol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation Format Evaluation](https://trello.com/c/rXMYBkRh/4-documentation-format-evaluation)

**Comment by M320Trololol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation Format Evaluation](https://trello.com/c/rXMYBkRh/4-documentation-format-evaluation)

**Comment by ibogicevic** [comment]
We decided to use markdown format both for technical and end-user-documentation.
