### ISSUE TITLE
Definition of Game

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#3]
Define the game and document the game story and all game rules as precise as possible.

**Comment by ibogicevic** [comment]
Estimated Efforts: 5h/8h

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#3 Definition of Game](https://trello.com/c/ykUWW8v9/5-3-definition-of-game)

**Comment by M320Trololol** [comment]
For all intents and purposes of Sprint 1, this is done in https://github.com/dhbw-stginf16a/Rebleyama/wiki/Definition-of-Game
