### ISSUE TITLE
Data Structure

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#4]
Define the (static) data structure of the program. Draw a UML class diagram.

**Comment by ibogicevic** [comment]
Estimated Efforts: 5h/5h

**Comment by danielrutz** [comment]
Need to know details on the rules/objects in game @M320Trololol 
dependent on #17 maybe also #5.

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#4 Data Structure](https://trello.com/c/87yTngm4/6-4-data-structure)

**Comment by M320Trololol** [comment]
@danielrutz Please provide a progress report to see if this can be closed
