### ISSUE TITLE
Sprint Retrospective for M1

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#43]
- We don't use Trello for the project anymore
- No to large subteams (maximum of two for normal-size tasks)
- Don't forget your expert role
- Define more tasks and subtasks

**Comment by ThoreKr** [comment]
A small addition:
- Label your issues to the certain subprojects 
  - client
  - server
  - lib (shared library between client and server)
  - libgdx
Multiple labels may be applied to an issue.
