### ISSUE TITLE
Initial Codebase

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#5]
Copy the code from the OpenSource Project SCADinspect and remove everything that is not needed for our program. Keep the JavaFX main frame, the structure of the toolbar (without unneeded buttons) and the about dialog (without specific content).

**Comment by ibogicevic** [comment]
Estimated Efforts: shouldn't be part, otherwise 5h/?

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #5 Initial Codebase](https://trello.com/c/CWkkJ1pK/7-5-initial-codebase)

**Comment by ibogicevic** [comment]
The code needn't be taken from SCADinspect. The hello-world-example from libGDX is perhaps a better choice.

**Comment by ibogicevic** [comment]
Closed as this will be done as part of #18
