### ISSUE TITLE
Planning of Multiscreen Implementation

### ISSUE THREAD

**Issue by johannaSommer** [dhbw-stginf16a/Rebleyama#55]
Because we are unexperience with this issue, we will research ways to connect different views/screens, so that you have a start screen in the beginning that then takes you to the game.

**Comment by ibogicevic** [comment]
This could be helpful: http://www.pixnbgames.com/blog/libgdx/how-to-make-a-splash-screen-in-libgdx/

**Comment by johannaSommer** [comment]
Menu Screen renders Menu and with button click the game gets rendered. In theory.
