### ISSUE TITLE
Proper cleanup

### ISSUE THREAD

**Issue by danielrutz** [dhbw-stginf16a/Rebleyama#65]
Some classes of libGDX implement the com.badlogic.gdx.utils.Disposable interface. That provides the method dispose(). An object that has such an interface MUST be disposed when not needed anymore, as not doing so leads to memory leaks (see [this wiki article of libGDX](https://github.com/libgdx/libgdx/wiki/Memory-management)). We are currently not cleaning up properly, this should be fixed.

**Comment by M320Trololol** [comment]
Assigning all the people working on the engine at the moment.
