### ISSUE TITLE
Complete Community profile

### ISSUE THREAD

**Issue by Oswaldbob** [dhbw-stginf16a/Rebleyama#69]
Complete needed steps for the following checklist: https://github.com/dhbw-stginf16a/Rebleyama/community

**Comment by ibogicevic** [comment]
Related document: https://github.com/dhbw-stginf16a/Rebleyama/blob/master/process.md

**Comment by johannaSommer** [comment]
Contributing file and code of conduct has been inserted, the last point (issue and pull request template) is missing because it does not make sense to implement it at this point.
