### ISSUE TITLE
Branching/Merging Concept

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#7]
Define the Branching/Merging/Contribution Concept and document it in a file process.md.

**Comment by ibogicevic** [comment]
Estimated Efforts: 1h(only making the concept)/2h

**Comment by ibogicevic** [comment]
We decided to use markdown format both for technical and end-user-documentation.

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #7: Branching/Merging Concept](https://trello.com/c/1CNMgZcx/10-issue-7-branching-merging-concept)
