### ISSUE TITLE
Select Skin for Scene2d UI 

### ISSUE THREAD

**Issue by Oswaldbob** [dhbw-stginf16a/Rebleyama#70]
Select one of the skins for the UI elements. 
Skin examples: https://github.com/czyzby/gdx-skins

**Comment by ibogicevic** [comment]
I'd prefer one of the following:
https://github.com/czyzby/gdx-skins/tree/master/sgx
https://github.com/czyzby/gdx-skins/tree/master/tracer
https://github.com/czyzby/gdx-skins/tree/master/vis
Any other opinions?

**Comment by M320Trololol** [comment]
I like the vis skin :) 

<iframe src="http://www.strawpoll.me/embed_1/15528306" style="width:680px;height:365px;border:0;">Loading poll...</iframe>

**Comment by M320Trololol** [comment]
Vis selected, closed
