### ISSUE TITLE
Decide on Pixmap-Pixel Colors 

### ISSUE THREAD

**Issue by Oswaldbob** [dhbw-stginf16a/Rebleyama#71]
Decide on an Pixel Color code for each tile that we use. The code will be used within the Map and Minimap. 

The Map can also be made by up to 4 different Color codes per tile.

**Comment by Xerf1** [comment]
![image](https://user-images.githubusercontent.com/5603062/39246457-f6fff9f0-4896-11e8-968f-8539276927f2.png)I think this will be sufficient for our purposes. Since you dont need Hex-codes or RGB values, here are just the names of the colours.

**Comment by Xerf1** [comment]
Colour the Minimap with 4 pixels for each Tile. 
One of the above terrain-types is assigned to each corner of each Tile. 
These can be accessed through the .tsx file.
@danielrutz should know how to access the Terrain type out of our code.
