### ISSUE TITLE
Decide on Multithreading for Client rendering 

### ISSUE THREAD

**Issue by Oswaldbob** [dhbw-stginf16a/Rebleyama#72]
Decide if we want to use multithreading for client rendering of the UI, Tiledmap, etc.

**Comment by ibogicevic** [comment]
As performance does not seem to be a big problem for the currently planned implementation, I propose to keep (for now) everything in one thread, close this issue, open a new one "Use Multithreading for Client rendering" and assign that issue to https://github.com/dhbw-stginf16a/Rebleyama/milestone/4.

**Comment by M320Trololol** [comment]
Theres also this: 

> The Stage and its constituents (like Actors and Listeners) are not thread-safe and should only be updated and queried from a single thread (presumably the main render thread). Methods should be reentrant, so you can update Actors and Stages from within callbacks and handlers.

from https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/Stage.html

which is why I second the  approach of keeping it single threaded since we heavily rely on stages.
