### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#8]
Define the structure of the folders in the repository by creating empty folders with .gitkeep-files and a descriptive document repo-structure.md

**Comment by ibogicevic** [comment]
Estimated Efforts: 2h/1h

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #8: Repository Structure](https://trello.com/c/Tr2fsU4S/11-issue-8-repository-structure)

**Comment by ThoreKr** [comment]
As the structure is defined by gradle and #23 is already closed this issue can be closed too.
