### ISSUE TITLE
Evaluation of Advertising

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#9]
Evaluate where we want to advertise the program, e.g. with a website, youtube-video, wiki, etc. and crete new issues accordingly.

**Comment by ibogicevic** [comment]
Estimated Efforts: 2h/2h

**Comment by johannaSommer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #9: Evaluation of Advertising](https://trello.com/c/dwvn0ALy/12-issue-9-evaluation-of-advertising)

**Comment by smilingGirl** [comment]
**Suggested Steps for Advertising**
1. Agree on channel to advertise through
- Tumblr/Wordpress/Sth-else Blog
- Facebook Page
- Youtube Channel

2. Ways to advertise
- Video
- Slogans
- Text Posts

**Comment by smilingGirl** [comment]
We have a tumblr now: 
https://rebleyama.tumblr.com/

**Comment by M320Trololol** [comment]
I think this can be closed, @ibogicevic @smilingGirl do you agree?

**Comment by ibogicevic** [comment]
I agree
