### ISSUE TITLE
Project Mailing List

### ISSUE THREAD

**Issue by ibogicevic** [dhbw-stginf16a/Rebleyama#92]
It would be good to have a mail address for the project, e.g. with ...@rebleyama.de and automatically forward the mails from there to some of our mail addresses. That would avoid that some of our private mail addresses can publicly be seen (https://github.com/dhbw-stginf16a/Rebleyama/pull/90/files/5fd1650450f9f2bc0116b3b0e7da68f05e20c414#diff-a1ee87dafebc22cbd96979f1b2b7e837)

**Comment by danielrutz** [comment]
Done. Please get in touch with me if someone from the team wants access onto the mailing list.
